name: Run Python Script

on:
  push:
    branches:
      - main  # Adjust branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'  # Specify your Python version

      - name: Run Python script
        run: |
          python Voice_q.py  # Specify the path to your Python script
